### PR TITLE
Add GitHub templates

### PR DESCRIPTION
**Pull request by mloskot**
Add [Issues template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

----

Do we want [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) too?

### CODE REVIEW

**Comment by lexicalunit** [comment]
Less useful with PR Templates as we can always just look at the code diff to see what the PR is doing.

**Comment by mloskot** [comment]
Yes, and PR description is often just the commit

**Comment by bryevdv** [comment]
I really wish GH would offer a feature to have a mandatory form to fill out, many users have no trouble deleting the template text without reading it, it seems.

**Comment by mloskot** [comment]
@bryevdv Yes, no-brainer feature. 

I'll keep being annoying requesting authors of incomplete submissions for details ;)

**Pull request merged**
