### PR TITLE
WIP: Rebase of mcg1969's converters branch

### PR DESCRIPTION
**Pull request by lexicalunit**

### CODE REVIEW

**Comment by lexicalunit** [comment]
@mcg1969 commit 14946f4 seems to get things passing on *NIX systems.

**Comment by mcg1969** [comment]
OK, at least I can examine the Windows tests now.

**Comment by mloskot** [comment]
Any updates on this (and #201)?

**Comment by mcg1969** [comment]
I'm afraid not. I just haven't had the opportunity; I'm not on the project that was utilizing this anymore. ;-(

**Comment by mloskot** [comment]
@mcg1969 Understood and no problem.
Thanks for your great contributions

**Comment by mloskot** [comment]
This PR should be closed, merged into master (or moved to PRs) in new repo https://github.com/nanodbc/nanodbc

**Comment by mloskot** [comment]
@lexicalunit Please, close this PR (apparently, I can not do it as i don't see the close button :))

I'm going to prepare new rebase of https://github.com/lexicalunit/nanodbc/pull/201

**Comment by mloskot** [comment]
@lexicalunit Please, close this PR.

**Pull request closed without merging**
