### PR TITLE
Fixed retrieving long strings from MySQL

### PR DESCRIPTION
**Pull request by saur0n**
For some reasons, nanodbc does not properly bind and retrieve long strings from/to MySQL (MariaDB). It cuts this strings to first 128 bytes. `blob_test()` does not cover this bug.
#216

### CODE REVIEW

**Comment by mloskot** [comment]
The test is failing on both, Linux ([Travis CI job 629.3](https://travis-ci.org/lexicalunit/nanodbc/jobs/164138086)) and Windows ([AppVeyor job 1.0.303](https://ci.appveyor.com/project/lexicalunit/nanodbc/build/1.0.303/job/j07fai4p6x85srko))

**Comment by saur0n** [comment]
Yes, I will try to bring fix for nanodbc (not for test) this week.

**Comment by saur0n** [comment]
All tests passed successfully.

**Comment by mloskot** [comment]
I'm travelling until the 13th of Nov, without laptop so can't really review
it. But, if all the current tests pass and the fix is covered with a test
too, sounds good to me.

When I'm back, I'll continue with bind functions refactoring. So better if
we merge pending PRs since the refactoring may be a bit intrusive.

**Pull request merged**
