### PR TITLE
CMake: Replace NANODBC_STATIC with BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by mloskot**
* [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) is standard CMake option (a global flag).
* `BUILD_SHARED_LIBS=ON` causes add_library to create shared libraries, automatically.
* Update README.md.
* Add shared target build to Travis CI.

------

Motivation: one custom option less; get closer to CMake recommended/best practices.

------

A good example of CMake configuration using the `BUILD_SHARED_LIBS` is FreeType2 project: http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/CMakeLists.txt
It shows how to use the option for OSX, distinguish `APPLE` vs `FRAMEWORK` modes.
I don't have access to Mac OS X myself though, so this part is missing from this PR.

### CODE REVIEW

**Comment by lexicalunit** [comment]
I'm getting an error when trying to compile this on my macOS machine:

```
$ make VERBOSE=1 nanodbc
/usr/local/Cellar/cmake/3.7.1/bin/cmake -H/Users/me/source/nanodbc -B/Users/me/source/nanodbc/build --check-build-system CMakeFiles/Makefile.cmake 0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 nanodbc
/usr/local/Cellar/cmake/3.7.1/bin/cmake -H/Users/me/source/nanodbc -B/Users/me/source/nanodbc/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.7.1/bin/cmake -E cmake_progress_start /Users/me/source/nanodbc/build/CMakeFiles 2
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/nanodbc.dir/all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/nanodbc.dir/build.make CMakeFiles/nanodbc.dir/depend
cd /Users/me/source/nanodbc/build && /usr/local/Cellar/cmake/3.7.1/bin/cmake -E cmake_depends "Unix Makefiles" /Users/me/source/nanodbc /Users/me/source/nanodbc /Users/me/source/nanodbc/build /Users/me/source/nanodbc/build /Users/me/source/nanodbc/build/CMakeFiles/nanodbc.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/nanodbc.dir/build.make CMakeFiles/nanodbc.dir/build
[ 50%] Building CXX object CMakeFiles/nanodbc.dir/src/nanodbc.cpp.o
/usr/local/bin/c++     -Wall -Werror -std=c++14 -stdlib=libc++   -I/usr/local/Cellar/unixodbc/2.3.4/include -o CMakeFiles/nanodbc.dir/src/nanodbc.cpp.o -c /Users/me/source/nanodbc/src/nanodbc.cpp
clang: error: argument unused during compilation: '-I /usr/local/Cellar/unixodbc/2.3.4/include' [-Werror,-Wunused-command-line-argument]
make[3]: *** [CMakeFiles/nanodbc.dir/src/nanodbc.cpp.o] Error 1
make[2]: *** [CMakeFiles/nanodbc.dir/all] Error 2
make[1]: *** [CMakeFiles/nanodbc.dir/rule] Error 2
make: *** [nanodbc] Error 2
```

**Comment by lexicalunit** [comment]
Hrm, if I revert to `master` I get the same build error.

**Comment by lexicalunit** [comment]
This looks good to me. I saw we merge it now, and then I can work on getting things to compile on my macOS machine and open another PR when I get it working.

**Comment by mloskot** [comment]
Thanks for the merge.

**Pull request merged**
